// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BootstrapOwner = __t.object("BootstrapOwner", {
  key: __t.string(),
  identity: __t.identity(),
});
export type BootstrapOwner = __Infer<typeof BootstrapOwner>;

export const ServiceDocuments = __t.object("ServiceDocuments", {});
export type ServiceDocuments = __Infer<typeof ServiceDocuments>;

export const ServiceIdentity = __t.object("ServiceIdentity", {
  identity: __t.identity(),
});
export type ServiceIdentity = __Infer<typeof ServiceIdentity>;

export const ServiceSequence = __t.object("ServiceSequence", {});
export type ServiceSequence = __Infer<typeof ServiceSequence>;

export const StateDocument = __t.object("StateDocument", {
  key: __t.string(),
  instance: __t.string(),
  kind: __t.string(),
  guildId: __t.string(),
  value: __t.string(),
  revision: __t.u64(),
});
export type StateDocument = __Infer<typeof StateDocument>;

export const StateMutation = __t.object("StateMutation", {
  key: __t.string(),
  kind: __t.string(),
  guildId: __t.string(),
  value: __t.option(__t.string()),
  expectedRevision: __t.u64(),
});
export type StateMutation = __Infer<typeof StateMutation>;

export const StateSequence = __t.object("StateSequence", {
  key: __t.string(),
  revision: __t.u64(),
});
export type StateSequence = __Infer<typeof StateSequence>;

