// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AuthorizeServiceReducer from "../authorize_service_reducer.js";
import MutateStateReducer from "../mutate_state_reducer.js";

export type AuthorizeServiceParams = __Infer<typeof AuthorizeServiceReducer>;
export type MutateStateParams = __Infer<typeof MutateStateReducer>;

